name: Deploy Frontend (Next.js) to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCLOUD_PROJECT }}
  GAR_LOCATION: us-central1 # O tu región
  SERVICE_NAME: frontend # Nombre servicio Cloud Run
  REGION: us-central1 # Región Cloud Run
  # NO necesitamos la variable intermedia aquí

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # --- Autenticación (Tu método actual) ---
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      # --------------------------------------

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Configure Docker
        run: gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev

      # Construir imagen pasando DIRECTAMENTE el secreto al build-arg con el nombre VITE_API_URL
      - name: Build Docker image
        run: |
          docker build \
            --build-arg VITE_API_URL=${{ secrets.API_BASE_URL }} \ # <-- Usa el secreto directamente
            -t ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }} \
            ./frontend # Asegúrate que el contexto sea la carpeta frontend

      # Subir imagen
      - name: Push Docker image
        run: |
          docker push ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}

      # Desplegar a Cloud Run pasando DIRECTAMENTE el secreto a la variable de entorno VITE_API_URL
      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          image: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
          # ---> Pasar la variable de entorno VITE_API_URL con el valor del secreto <---
          env_vars: |-
            VITE_API_URL=${{ secrets.API_BASE_URL }} # <-- Usa el secreto directamente
            PORT=8080
            NODE_ENV=production
          flags: --allow-unauthenticated

      - name: Show Deployed URL
        run: echo "Service deployed to ${{ steps.deploy.outputs.url }}"