name: Deploy Frontend (Next.js) to Cloud Run (DEBUG URL)

on:
  push:
    branches:
      - main # O la rama donde está el código del frontend

env:
  PROJECT_ID: ${{ secrets.GCLOUD_PROJECT }}
  GAR_LOCATION: us-central1
  SERVICE_NAME: frontend
  REGION: us-central1
  # No necesitamos variable para nombre de secreto aquí

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout Frontend repository code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }} # O tu WIF

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Configure Docker
        run: gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev --quiet

      # Construir imagen SIN build-arg para la URL de la API
      - name: Build Docker image (Frontend)
        run: |
          docker build \
            -t ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }} \
            ./frontend # Asume contexto frontend/

      # Subir imagen
      - name: Push Docker image (Frontend)
        run: |
          docker push ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}

      # Desplegar a Cloud Run con URL HARDCODED en env_vars (SOLO PARA DEBUG)
      - name: Deploy Frontend to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          image: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
          # --- URL Hardcodeada ---
          env_vars: |-
            PYTHON_API_URL=https://api-551745267811.us-central1.run.app
            PORT=8080
            NODE_ENV=production
          # ----------------------
          flags: --allow-unauthenticated

      - name: Show Deployed URL
        run: echo "Frontend Service deployed to ${{ steps.deploy.outputs.url }}"