name: Deploy Frontend to Cloud Run

on:
  push:
    branches:
      - master  # usa "master" o "main", según la rama principal de tu repo

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout: clona el repositorio en el runner
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. Autenticar a Google Cloud usando el secreto
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      # 3. Configurar el SDK de Google Cloud
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT }}

      # 4. Configurar autenticación de Docker para Artifact Registry (us-central1)
      - name: Configure Docker authentication
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      # 5. Construir la imagen Docker usando la carpeta "frontend" como contexto
      - name: Build Docker image
        run: |
          docker build -t us-central1-docker.pkg.dev/${{ secrets.GCLOUD_PROJECT }}/frontend/frontend:${{ github.sha }} ./frontend

      # 6. Subir la imagen a Artifact Registry
      - name: Push Docker image
        run: |
          docker push us-central1-docker.pkg.dev/${{ secrets.GCLOUD_PROJECT }}/frontend/frontend:${{ github.sha }}

      # 7. Desplegar la imagen en Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy frontend \
            --image us-central1-docker.pkg.dev/${{ secrets.GCLOUD_PROJECT }}/frontend/frontend:${{ github.sha }} \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated
